name: Run Fresh Install Script on Production push

on:
  push:
    branches:
      - production

jobs:
  run-script:
    runs-on: self-hosted

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Run Fresh Install Script
        run: |
          chmod +x fresh_install.sh
          ./fresh_install.sh
