on:
  push:
    branches:
      - Production 
  pull_request:
    branches:
      - Production 
  workflow_dispatch:
  
jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - name: Run a multi-line script
        run: | 
          echo installeerime uue tunniplaani,
          echo valmis
          
          
    
