name: Deploy Workflow
on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Change to development directory
        run: cd development

      - name: Change to client directory
        run: cd client

      - name: Install dependencies
        run: npm i

      - name: Go back to the previous directory
        run: cd ..

      # Siin saate lisada rohkem samme vastavalt vajadusele

      - name: Execute git pull
        run: git pull reponame

      # Lisa siia rohkem käske vastavalt vajadusele
